import { useEffect, useRef, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import './LockScreen.css'
export default function LockScreen(){
 const navigate=useNavigate(),[time,setTime]=useState(new Date()),[unlocking,setUnlocking]=useState(false),start=useRef(null)
 useEffect(()=>{const id=setInterval(()=>setTime(new Date()),1000);return()=>clearInterval(id)},[])
 function unlock(){if(unlocking)return;setUnlocking(true);setTimeout(()=>navigate('/home'),360)}
 return <div className={`ipad-frame lock-root ${unlocking?'lock-exit':''}`} onPointerDown={e=>{start.current=e.clientY}} onPointerUp={e=>{if(start.current!==null&&start.current-e.clientY>60)unlock();start.current=null}}><div className="ipad-wallpaper"/><div className="lock-content"><div className="lock-symbol"><svg width="18" height="21" viewBox="0 0 24 28" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true"><rect x="4" y="12" width="16" height="13" rx="3"/><path d="M7 12V8a5 5 0 0 1 10 0v4"/><path d="M12 17v3"/></svg></div><p className="lock-date">{time.toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric'})}</p><div className="lock-time">{time.toLocaleTimeString('en-US',{hour:'2-digit',minute:'2-digit',hour12:false})}</div><div className="lock-identity"><span className="lock-identity-line"/><p>Ayush’s iPad</p><span className="lock-identity-line"/></div><div className="lock-mini-widgets"><span>⌘<small>Software engineer</small></span><span>◉<small>VIT Chennai</small></span><span>✦<small>Endlessly curious</small></span></div><div className="lock-notifs"><button className="lock-notif" onClick={()=>navigate('/about')}><span className="lock-notice-icon">◉</span><span className="lock-notice-copy"><span><b>Contacts</b><small>Welcome</small></span><strong>Hey, I’m Ayush Agrawal.</strong><p>Software engineer. Curious mind. Your next collaborator.</p></span></button><button className="lock-notif" onClick={()=>navigate('/projects')}><span className="lock-notice-icon project-notice">⊞</span><span className="lock-notice-copy"><span><b>Projects</b><small>Explore</small></span><strong>There’s a lot to discover.</strong><p>11 projects across AI, full-stack development, and Web3.</p></span></button></div><button className="unlock-button" onClick={unlock}><span>⌃</span>Click or swipe up to open</button></div><p className="lock-corner-note">Designed to be explored.</p></div>
}

