import { useEffect, useLayoutEffect, useRef, useState } from 'react'
import { useLocation, useNavigate } from 'react-router-dom'
import { useTheme } from '../context/ThemeContext'
import { useAudio } from '../context/AudioContext'
import { projects } from '../data/projects'
import MusicToggle from './MusicToggle'
import ClickFeedback from './ClickFeedback'
import NavigationIcon from './NavigationIcon'

function Panel({name,children,onClose,className=''}) {
 const ref=useRef(null)
 useEffect(()=>{const previous=document.activeElement;ref.current.showModal();return()=>previous?.focus()},[])
 return <dialog ref={ref} className={`os-panel ${className}`} aria-label={name} onCancel={onClose} onClick={e=>{if(e.target===ref.current)onClose()}}><div className="os-panel-heading"><h2>{name}</h2><button onClick={onClose} aria-label={`Close ${name}`}><NavigationIcon close /></button></div>{children}</dialog>
}
const initialNotices=[{id:'welcome',icon:'✦',title:'Welcome to my corner of the internet',app:'PORTFOLIO',text:'I’m Ayush. Tap to explore the person behind the projects.',path:'/about'},{id:'projects',icon:'⊞',title:'11 ideas. Built into reality.',app:'PROJECTS',text:'AI, full-stack, and Web3. Take a look around.',path:'/projects'},{id:'resume',icon:'↓',title:'The full story, in one document',app:'FILES',text:'My résumé is ready when you are.',path:'/Resume.pdf'}]
const apps=[{label:'Home',path:'/home',icon:'⌂',color:'#eb825d'},{label:'Projects',path:'/projects',icon:'⊞',color:'#468cf0'},{label:'About Me',path:'/about',icon:'◉',color:'#a18be0'},{label:'Experience',path:'/experience',icon:'▣',color:'#63b395'},{label:'Skills',path:'/skills',icon:'ϟ',color:'#e3aa4c'},{label:'Contact',path:'/contact',icon:'✉',color:'#9980d7'}]
function loadRecent(){try{return JSON.parse(sessionStorage.getItem('ipad-recents')||'[]').map(p=>p==='/about?tab=Skills'?'/skills':p==='/about?tab=Experience'?'/experience':p).filter(p=>apps.some(a=>a.path===p))}catch{return []}}
export default function AppSwitcher({children}) {
 const navigate=useNavigate(),location=useLocation(),{theme,setTheme,themes}=useTheme(),{isMuted,isAudioBusy,toggleMute}=useAudio()
 const [panel,setPanel]=useState(null),[query,setQuery]=useState(''),[time,setTime]=useState(new Date()),[recents,setRecents]=useState(loadRecent),[seen,setSeen]=useState(''),[notices,setNotices]=useState(initialNotices),[brightness,setBrightness]=useState(100),[focus,setFocus]=useState(false)
 const start=useRef(null),device=useRef(null),content=useRef(null)
 useLayoutEffect(()=>{
   if(window.matchMedia('(prefers-reduced-motion: reduce)').matches)return
   const animation=content.current?.animate([
     {opacity:.4},
     {opacity:1}
   ],{duration:180,easing:'cubic-bezier(.22,1,.36,1)'})
   return()=>animation?.cancel()
 },[location.pathname])
 const path=location.pathname+location.search,locked=location.pathname==='/'
 if(seen!==path){setSeen(path);if(apps.some(a=>a.path===path))setRecents(r=>[path,...r.filter(p=>p!==path)].slice(0,8))}
 useEffect(()=>{try{sessionStorage.setItem('ipad-recents',JSON.stringify(recents))}catch{/* Session history is optional. */}},[recents])
 useEffect(()=>{const id=setInterval(()=>setTime(previous=>{const next=new Date();return Math.floor(previous.getTime()/60000)===Math.floor(next.getTime()/60000)?previous:next}),1000);const key=e=>{if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();setPanel(v=>v==='Spotlight'?null:'Spotlight')}if(e.altKey&&e.key==='Tab'){e.preventDefault();setPanel('Recent Apps')}if(e.key==='Escape')setPanel(null)};window.addEventListener('keydown',key);return()=>{clearInterval(id);window.removeEventListener('keydown',key)}},[])
 function go(p){const recent=p.startsWith('/projects')?'/projects':p;if(apps.some(a=>a.path===recent))setRecents(r=>[recent,...r.filter(x=>x!==recent)]);setPanel(null);setQuery('');navigate(p)}
 function openNotice(n){if(n.path.endsWith('.pdf'))window.open(n.path,'_blank','noopener,noreferrer');else go(n.path)}
 const results=[...apps,...projects.map(p=>({label:p.title,path:`/projects?q=${encodeURIComponent(p.title)}`,icon:'⊞',color:p.typeColor}))].filter(a=>a.label.toLowerCase().includes(query.toLowerCase()))
 return <div className="device-stage"><div className="device-frame" ref={device}><div className="camera-dot"/><div className={`device-screen ${!locked&&location.pathname!=="/home"?"app-is-open":""}`}><div className="ipad-wallpaper"/><div className="os-status" onPointerDown={e=>{start.current=e.clientY;e.target.closest("button")?.setPointerCapture(e.pointerId)}} onPointerUp={e=>{if(start.current!==null&&e.clientY-start.current>25){const rect=e.currentTarget.getBoundingClientRect();setPanel(e.clientX>rect.left+rect.width*.7?"Control Center":"Notification Center")};start.current=null}}><button aria-label="Open Notification Center" onClick={()=>setPanel('Notification Center')}>{time.toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit'})}<span>{time.toLocaleDateString('en-US',{weekday:'short',month:'short',day:'numeric'})}</span>{!focus&&notices.length>0&&<i className="notification-dot"/>}</button><span className="device-owner">Ayush’s iPad</span><button aria-label="Open Control Center" onClick={()=>setPanel('Control Center')}><span>{focus?'☾':''}</span><svg width="17" height="15" viewBox="0 0 24 20" fill="none" stroke="currentColor" strokeWidth="2.4"><path d="M2 5q10-8 20 0M6 10q6-5 12 0M10 15q2-2 4 0"/></svg><span>100%</span><span className="status-battery"><span className="status-battery-fill" style={{display:'block'}}/></span></button></div><ClickFeedback/><MusicToggle/><div ref={content} className="os-content" inert={panel?true:undefined}>{children}</div><div className="brightness-veil" style={{opacity:(100-brightness)/125}}/>
 {location.pathname==="/home"&&<button className="os-search-pill" onClick={()=>setPanel("Spotlight")} aria-label="Search portfolio">⌕ <span>Search</span></button>}{!locked&&<div className="system-tools"><button onClick={()=>go('/home')} aria-label="Go to Home Screen">⌂</button><button onClick={()=>setPanel('Spotlight')} aria-label="Open Spotlight">⌕</button><button onClick={()=>setPanel('Recent Apps')} aria-label="Open Recent Apps">▱</button><button onClick={()=>go('/')} aria-label="Lock iPad"><svg width="18" height="21" viewBox="0 0 24 28" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true"><rect x="4" y="12" width="16" height="13" rx="3"/><path d="M7 12V8a5 5 0 0 1 10 0v4"/><path d="M12 17v3"/></svg></button></div>}
 <button className="os-home-indicator" aria-label={locked?'Unlock iPad':'Home indicator: click for home, swipe up for recent apps'} onPointerDown={e=>{start.current=e.clientY;e.target.closest("button")?.setPointerCapture(e.pointerId)}} onPointerUp={e=>{if(start.current===null)return;const delta=start.current-e.clientY;start.current=null;if(delta>35&&!locked)setPanel('Recent Apps');else go('/home')}} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();go('/home')}}}><span/></button>
 {panel==='Notification Center'&&<Panel name={panel} onClose={()=>setPanel(null)} className="notifications-panel"><div className="notification-clock">{time.toLocaleTimeString('en-US',{hour:'2-digit',minute:'2-digit',hour12:false})}</div><p className="notification-date">{time.toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric'})}</p><div className="notice-toolbar"><span>{notices.length} notifications</span>{notices.length>0&&<button onClick={()=>setNotices([])}>Clear all</button>}</div>{notices.map(n=><div className="os-notice" key={n.id}><button className="notice-open" onClick={()=>openNotice(n)}><span className={`notice-icon notice-${n.id}`}>{n.icon}</span><span><small>{n.app}</small><strong>{n.title}</strong><p>{n.text}</p></span></button><button className="notice-dismiss" aria-label={`Dismiss ${n.app} notification`} onClick={()=>setNotices(v=>v.filter(x=>x.id!==n.id))}>×</button></div>)}{!notices.length&&<p className="os-empty">You’re all caught up.</p>}</Panel>}
 {panel==='Control Center'&&<Panel name={panel} onClose={()=>setPanel(null)} className="control-panel"><div className="control-grid"><button className={focus?'control-tile enabled':'control-tile'} onClick={()=>setFocus(!focus)} aria-pressed={focus}><b>☾</b><strong>Focus</strong><small>{focus?'On · notification badge hidden':'Off'}</small></button><button className={!isMuted?'control-tile enabled':'control-tile'} onClick={toggleMute} disabled={isAudioBusy} aria-pressed={!isMuted}><b>♫</b><strong>Ambient sound</strong><small>{isMuted?'Tap to play':'Playing · tap to mute'}</small></button><label className="brightness-control"><span>☀ <strong>Brightness</strong><small>{brightness}%</small></span><input type="range" min="35" max="100" value={brightness} onChange={e=>setBrightness(Number(e.target.value))} aria-label="Screen brightness"/></label><div className="wallpaper-control"><h3>Wallpaper</h3><div>{Object.values(themes).map(t=><button key={t.id} aria-label={`${t.name} wallpaper`} aria-pressed={theme===t.id} onClick={()=>setTheme(t.id)} style={{background:`linear-gradient(130deg,${t.preview.join(',')})`}}>{theme===t.id?'✓':''}<span>{t.name}</span></button>)}</div></div><button className="control-tile" onClick={()=>go('/')}><b><svg width="18" height="21" viewBox="0 0 24 28" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true"><rect x="4" y="12" width="16" height="13" rx="3"/><path d="M7 12V8a5 5 0 0 1 10 0v4"/><path d="M12 17v3"/></svg></b><strong>Lock screen</strong><small>Back to the beginning</small></button><button className="control-tile" onClick={()=>{if(document.fullscreenElement)document.exitFullscreen().catch(()=>{});else device.current.requestFullscreen?.().catch(()=>{})}}><b>⛶</b><strong>Full screen</strong><small>Immerse yourself</small></button></div><p className="control-footnote">Your own little workspace. Make yourself at home.</p></Panel>}
 {panel==='Spotlight'&&<Panel name={panel} onClose={()=>setPanel(null)} className="spotlight-panel"><input className="spotlight-input" autoFocus aria-label="Search apps and projects" placeholder="Search apps and projects" value={query} onChange={e=>setQuery(e.target.value)}/><p className="spotlight-label">{query?'SEARCH RESULTS':'SIRI SUGGESTIONS'}</p><div className="spotlight-results">{results.map(a=><button key={a.path} onClick={()=>go(a.path)}><span style={{background:a.color}}>{a.icon}</span><strong>{a.label}</strong><small>Open ↗</small></button>)}{!results.length&&<p className="os-empty">No results. Try “Projects” or “LeetCoach”.</p>}</div><p className="control-footnote">Ctrl / ⌘ K to search · Esc to close</p></Panel>}
 {panel==='Recent Apps'&&<Panel name={panel} onClose={()=>setPanel(null)} className="recents-panel"><p className="recents-hint">Pick up where you left off.</p><div className="recent-grid">{recents.map(p=>{const app=apps.find(a=>a.path===p);return <article className="recent-app" key={p}><div className="recent-title"><span style={{background:app.color}}>{app.icon}</span><strong>{app.label}</strong><button aria-label={`Close ${app.label} recent app`} onClick={()=>setRecents(r=>r.filter(x=>x!==p))}>×</button></div><button className={`recent-preview ${p==='/home'?'recent-home':''}`} onClick={()=>go(p)} aria-label={`Resume ${app.label}`}>{p==='/skills'?<div className="recent-specific recent-skills"><span>ϟ</span><h3>My developer toolbox</h3><p>Languages · Web · AI · Blockchain</p><div><b>React.js</b><b>Python</b><b>Solidity</b><b>Node.js</b></div></div>:p==='/experience'?<div className="recent-specific recent-experience"><span>▣</span><h3>Learning by doing</h3><p>AI Club · VIT Chennai</p><strong>Operations Lead</strong><small>Mar 2024 — Present</small></div>:p==='/contact'?<div className="recent-specific recent-contact"><span>✉</span><h3>Say hello.</h3><p>Ayush Agrawal</p><strong>New message</strong><small>Your draft stays with you.</small></div>:p==='/projects'?<><div className="mini-toolbar">Projects <span>All projects</span></div><div className="mini-projects">{projects.slice(0,4).map(p=><img src={p.image} alt="" key={p.id}/>)}</div></>:p==='/home'?<><img className="mini-avatar" src="/animated_ayush.png" alt=""/><h3>Hey, I’m Ayush.</h3><div className="mini-icons">{apps.map(a=><span key={a.path} style={{background:a.color}}>{a.icon}</span>)}</div></>:<><img className="mini-avatar" src="/animated_ayush.png" alt=""/><h3>{app.label==='About Me'?'Ayush Agrawal':app.label}</h3><p>Software Engineer · VIT Chennai</p><div className="mini-stats"><b>9.20<small>CGPA</small></b><b>300+<small>LeetCode</small></b></div></>}</button></article>})}</div>{!recents.length&&<p className="os-empty">No recent apps. Open an app from the Home Screen to get started.</p>}<button className="recent-home-button" onClick={()=>go('/home')}>⌂ Home Screen</button></Panel>}
 </div></div><div className="device-caption"><span>AYUSH AGRAWAL <i>✦</i> A PORTFOLIO, REIMAGINED.</span><span>Tap to explore. Swipe to switch. Make yourself at home.</span></div></div>
}








